version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: clinic_db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Password"
      MSSQL_PID: "Express"
    volumes:
      - clinic_data:/var/opt/mssql

  clinictrialapi:
    build:
      context: .
      dockerfile: ClinicTrialApi/Dockerfile
    container_name: clinic_api
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=ClinicDb;User Id=sa;Password=YourStrong!Password;Encrypt=True;TrustServerCertificate=True;"

volumes:
  clinic_data:
